name: CI/CD Pipeline

on:
  push:
    paths-ignore:
      - "api/static/*.json"
      - ".github/workflows/**"
      - "README.md"
      - "LICENSE"
      - "codecov.yml"
      - "requirements-dev.txt"
      - ".env.example"
    branches: [main]
  workflow_dispatch: # allow manual trigger


jobs:
  run-tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    name: Deploy Application
    needs:
      - run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -exuo pipefail
            cd /opt/nba_stables
            git pull origin main
            find . -type f -name "*.py[co]" -delete -or -type d -name "__pycache__" -delete
            docker compose --profile prod up -d --build
            docker image prune -f
            cp /opt/nba_stables/Caddyfile /etc/caddy/Caddyfile
            sudo systemctl reload caddy
