name: CI/CD Pipeline

permissions: {}

on:
  push:
    paths-ignore:
      - ".github/workflows/**"
      - "README.md"
      - "LICENSE"
      - "codecov.yml"
      - "requirements-dev.txt"
      - ".env.example"
      - "dependabot.yml"
    branches: [main]
  workflow_dispatch: # allow manual trigger


jobs:
  run-tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    name: Deploy Application
    needs:
      - run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          version: "1.8.4"
          script: |
            set -exuo pipefail
            cd /opt/nba_stables
            git pull origin main
            find . -depth \( -type f -name "*.py[co]" -o -type d -name "__pycache__" \) -delete || true
            docker compose --profile prod build
            docker compose --profile prod up -d --wait
            docker image prune -f
            if ! diff -q /opt/nba_stables/Caddyfile /etc/caddy/Caddyfile >/dev/null 2>&1; then
              cp /opt/nba_stables/Caddyfile /etc/caddy/Caddyfile
              sudo systemctl reload caddy
            fi
